### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by huard** [bird-house/birdhouse-deploy#140] opened 2021-03-31 18:36 UTC
There is no license that accompany the code.

**Comment by Zeitsperre** [comment] 2021-03-31 18:58
@huard @cehbrecht Apache v2 is the standard we've used the Ouranos side to ensure no one uses our logos. Is there a convention for Birdhouse? (GPL?)

**Comment by huard** [comment] 2023-02-06 16:22
Unless there is an objection, let's go with Apache v2 then.

**Comment by tlvu** [comment] 2023-04-13 04:11
Dupe of https://github.com/bird-house/birdhouse-deploy/issues/309

**Closed by tlvu** 2023-04-13 04:11 UTC
Labels: question
